### ISSUE TITLE
Pusher authend point URL, sends POST request but data is corrupt

### ISSUE THREAD

**Issue by codesavvy** [pusher/pusher-js#241] opened 2017-07-12 06:41 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
function createPusherInstance(token) {
  if (pusherKey) {
    return new Pusher(pusherKey, {
      scheme: "HTTPS",
      port: 443,
      encrypted: true,
      authEndpoint: '/api/v1/mobile/chats/auth',
      auth: {
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `xxxxx`
        }
      }
    });
  }
}

This is how I create pusher instance and while the pusher sends request to auth-api, parameters are not correct and rails server is raising 'ActionDispatch::ParamsParser::ParseError' because the parameters coming with the POST request is not in post data format, but as query parameters

Rails bug report:

An ActionDispatch::ParamsParser::ParseError occurred in api_chats#auth:

  822: unexpected token at 'socket_id=218464.904349&channel_name=presence-bbf0bed3-95b8-440f-bba7-0d9a332dfe33'
  lib/rack/url_resolver.rb:29:in `call'

-------------------------------
Request:
-------------------------------

  * URL        : https://xxxx.com/api/v1/mobile/chats/auth
  * HTTP Method: POST
  * IP address : xxx.xxx.xxx.xxx
  * Parameters : {"controller"=>"api/v1/mobile/api_chats", "action"=>"auth"}
  * Timestamp  : 2017-07-11 20:16:56 +0530
  * Server : name
  * Rails root : /rails/root/app_directory 
  * Process: 10561

-------------------------------
Session:

Am I missing something or is it a bug from Pusher side?

**Comment by hph** [comment] 2017-07-12 11:25
@codesavvy The problem appears to be on your side - you're passing in headers saying that the body is in JSON but your auth endpoint gets it as urlencoded form data and from what I can tell, that's why your backend throws (since by the header it expects JSON, but there is none). Your backend can (almost certainly) parse an urlencoded body so I'd try removing the custom header you're passing in and see if that does the trick. I'm closing this now because it doesn't appear to be an issue on our side, but don't hesitate to let us know again if you think there's an actual bug here.

**Closed by hph** 2017-07-12 11:25 UTC

**Comment by fabbballin** [comment] 2017-12-10 07:20
@hph the problem appears to be in how the pusher-js library is setting `Content-Type` headers. It doesn't allow `application/json` solo. Is this by design or a bug?

Here's my header in FF, `Content-Type: application/x-www-form-urlencoded, application/json`. And my Pusher config:

```
...
        authEndpoint: '/auth/pushers',
        auth: {
            headers: {
                'Authorization': token,
                'Content-Type': 'application/json',
                'Accept': 'application/agent.v1+json'
            }
        }
```

Notice how `application/x-www-form-urlencoded` is prepended? Additionally it's not sending the request as JSON, but urlencoded.

The issue appears here: https://github.com/pusher/pusher-js/blob/185efd25dc0ca6e3cd4e95e07da0271a93de104d/src/runtimes/worker/auth/fetch_auth.ts#L7

**Comment by neomrc** [comment] 2019-07-10 05:51
Any updates here?

**Comment by hassanelhoseny** [comment] 2024-05-30 08:41
i issues . i cant send header to my authEnd point header do not send 

const initializePusher = async () => {
  try {
    await pusher.init({
      apiKey: "89a7fe3d2c1fb636b087",
      cluster: "eu",
      authEndpoint: `${ApiURL}/api/v1/chat/auth`,
      auth: {
        headers: {
          authorization: "XXXX",
        },
      },
    });

    await pusher.connect();
    // console.log("Pusher connected successfully");
  } catch (e) {
    console.log(`Error: ${e}`);
  }
};

i cant send header to this end point
