### ISSUE TITLE
Mobile: doesn't receive messages after a network change

### ISSUE THREAD

**Issue by Bartalog** [pusher/pusher-js#265] opened 2018-01-08 21:50 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
On mobile (Android): after switching from 4G to wifi, the channel I am listening to doesn't receive messages anymore.
Same problem when switching from wifi to 4G.

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem**
On mobile (Android), visit https://storage.googleapis.com/cool-maze-draft/pusher-network-change/index.html
_Before_ any network change, clicking the button updates the "Target" zone.
_After_ any network change, clicking the button doesn't work anymore (the message is sent, but not received).

**What is the expected behavior?**
Switching network doesn't affect Pusher channels listened to.

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
Pusher 4.2.2
It didn't work in previous 4.* versions either.

**Anything to add?**
Thank you for making Pusher such a cool tool, you guys rock!

**Comment by Bartalog** [comment] 2018-01-08 21:51
This is related to #223, and possibly to #260

**Comment by hph** [comment] 2018-01-09 10:28
Hi, @Bartalog

Thanks for submitting the issue and for creating the demo app in order to make it easy to test. Strangely enough, I’m not seeing the same issues on my own Android device. Just to make sure I’m not missing something, here’s what I did:

1) Disconnected from the wi-fi connection and disabled mobile data.
2) Re-enabled mobile data, connected to the 4G network, and opened the demo website.
3) Clicked on the button and saw the target area update as expected.
4) Disconnected from the mobile network and re-enabled the wi-fi.
5) After my phone connected to the network I pressed the button again. The text updated as it did previously.
6) I did this a few times and tried a few different things, like both connecting manually to the networks and allowing the phone to do it automatically, but the end result was always the same.

Could it be that you didn’t test the app that you submitted to reproduce the issue? I’m not saying that there’s nothing wrong here, I trust that something went wrong in your actual app where you saw the issue, but this demo app might not properly capture it. Let me know if this is the case. If it isn't, could you share more details about your environment? For instance, are you using React Native or are you building a web app?

Thanks!

**Comment by Bartalog** [comment] 2018-01-09 13:19
Hi Haukur, thanks for this prompt update.

Yes I have tested the sample demo, here are the details of my phone where I consistently experience the bug :

- Samsung Galaxy S6, Android 7.0, Kernel 3.10.61-10940776, Chrome 63.0.3239.111

Then I tried on 2 other, more recent phones, and it turns out I can't reproduce the bug on them! Just like when you tried yourself :

- Pixel 1 XL, Android 8.1.0,  Kernel 3.18.70-g520f6eb, Chrome 63.0.3239.111
- Pixel 2, Android 8.1.0, Chrome Canary 65.0.3315.0

So far, it seems that recent Android phones are not impacted. In my tests I always let the phone automatically switch network when I turn wifi on/off.

The sample app uses only JS, jQuery, and sources remote lib https://js.pusher.com/4.2.2/pusher.min.js .
The actual app I'm building uses JS, React, npm package pusher-js ; (not React Native).

**Comment by hph** [comment] 2018-01-09 17:09
Interesting, thanks for testing the other devices. I'm also using Android 8.1.0 and, as you've suggested, this could be related to the Android version. I'll make some tests on older versions of the OS to debug this.

**Comment by hph** [comment] 2018-01-09 17:50
I just tried running Android 7.1 on a virtual machine and wasn't able to reproduce this either. To be fair, that doesn't really reproduce your environment, since you're running 7.0 on an actual mobile device. I used a mobile hotspot connection to simulate having multiple different networks, but that might still not really reproduce the same environment. I might experiment with downgrading an android device to this version. Could you try upgrading yours to 8.0 and see if the issue goes away?

**Comment by Bartalog** [comment] 2018-01-16 23:44
Hi, my phone can't upgrade to 8.0 (new OS would need to be pushed by carrier).

I tested on another phone: Samsung Galaxy S8, Android 7.0, and could *not* reproduce the bug on it.

That's ~ 5 to 1, which makes my first phone look odd. I suggest we close the issue. Thanks again for your time!

**Comment by sunweiyang** [comment] 2018-01-26 18:40
I'm seeing this issue in our users on Android 7.0, Galaxy Note 5 --  @hph and @Bartalog, I'd like to request that this issue remain open.

**Comment by sunweiyang** [comment] 2018-01-26 18:51
By the way, our issue was observed in 4.2.1 -- the #251 pull request referenced in #223 appears to have been merged in by then. Were there additional changes that were meant to help this issue in 4.2.2?

**Comment by zz** [comment] 2019-09-19 14:26
Does this issue fixed?

**Comment by Bartalog** [comment] 2019-09-19 14:50
Hi, in addition to the above I have 2 recent phones that **are not** impacted:
- Xiaomi Mi 9, Android 9, Chrome 77
- Pixel 3, Android 9, Chrome 77

I don't worry too much about the old phones like my Samsung S6. @sunweiyang is it still a problem for you?

**Closed** 2021-02-03 16:15 UTC
Labels: react-native, wontfix
