### ISSUE TITLE
Permanent requests to Pusher in iframe in Firefox (at least 43.0.4 and still in 44.0)

### ISSUE THREAD

**Issue by abaranoff** [pusher/pusher-js#139] opened 2016-01-27 16:38 UTC
When I put Pusher connection code into iframe and open in Firefox 43.0.4+ I see permanent HTTP requests to the Pusher's server in Firebug Network Panel. Here is the output:

```
GET 844d79e50f7fe5624d53?pro...rsion=3.0.0&flash=false  101 Switching Protocols ws.pusherapp.com    0 B 52.23.216.193:80    289ms
GET 1?session=NTA5NjY0MDkx&b...CI6MTQ1MzkxMTM3NDk0N31d  200 OK  stats.pusher.com    67 B    104.237.141.160:80  340ms
GET 844d79e50f7fe5624d53?pro...rsion=3.0.0&flash=false  101 Switching Protocols ws.pusherapp.com    0 B 52.23.216.193:80    444ms
GET 2?session=NTA5NjY0MDkx&b...CI6MTQ1MzkxMTM3NjkyM31d  200 OK  timeline17.pusher.com   67 B    104.237.141.160:80  338ms
GET 844d79e50f7fe5624d53?pro...rsion=3.0.0&flash=false  101 Switching Protocols ws.pusherapp.com    0 B 52.23.216.193:80    454ms
GET 3?session=NTA5NjY0MDkx&b...CI6MTQ1MzkxMTM3OTAwNH1d  200 OK  timeline17.pusher.com   67 B    104.237.141.160:80  348ms
GET 844d79e50f7fe5624d53?pro...rsion=3.0.0&flash=false  101 Switching Protocols ws.pusherapp.com    0 B 52.23.216.193:80    262ms
GET 4?session=NTA5NjY0MDkx&b...CI6MTQ1MzkxMTM4MDg4MX1d  200 OK  timeline17.pusher.com   67 B    104.237.141.160:80  333ms
GET 844d79e50f7fe5624d53?pro...rsion=3.0.0&flash=false  101 Switching Protocols ws.pusherapp.com    0 B 52.23.216.193:80    471ms
GET 5?session=NTA5NjY0MDkx&b...CI6MTQ1MzkxMTM4Mjg0OX1d  200 OK  timeline17.pusher.com   67 B    104.237.141.160:80  345ms
GET 844d79e50f7fe5624d53?pro...rsion=3.0.0&flash=false  101 Switching Protocols ws.pusherapp.com    0 B 52.23.216.193:80    475ms
GET 6?session=NTA5NjY0MDkx&b...CI6MTQ1MzkxMTM4NTEwOX1d  200 OK  timeline17.pusher.com   67 B    104.237.141.160:80  336ms
GET 844d79e50f7fe5624d53?pro...rsion=3.0.0&flash=false  101 Switching Protocols ws.pusherapp.com    0 B 52.23.216.193:80    262ms

.... and so on. Every second.
```

I wrote about this problem to Pusher's support and they adviced me to create issue here. They was able to reproduce this behaviour and confirm it.

Please see attached files to reproduce it yourself.

 Configuration: Windows 7, Firefox 43.0.4 (tried on 44.0, problem still occurs)

Please Note: 
1. All works as expected when you use Pusher without iframe in Firefox. 
2. All works as expected in Chrome browser (both with and without iframe)

[test-pusher.zip](https://github.com/pusher/pusher-js/files/106940/test-pusher.zip)

**Comment by xpurpur** [comment] 2016-01-30 13:00
Forgot to say: Messages don't deliver to iframe as well.

**Comment by vivangkumar** [comment] 2016-02-01 11:13
@pl Any thoughts on this?

**Comment by hph** [comment] 2018-01-05 10:04
I was able to reproduce this issue in Firefox version 44. However, this issue appears to have been fixed in version 47 or earlier, and it hasn't regressed since then. I'm unable to reproduce this issue in version 57, which is the latest version of the browser. Since Firefox updates automatically and there haven't been any other reports of this issue I think it's safe to close it for now. Please do let us know if this is still affecting you in any way.

**Closed by hph** 2018-01-05 10:04 UTC
Labels: Question
