### ISSUE TITLE
v5: presenceChannel.members is undefined when subbing to multiple channels

### ISSUE THREAD

**Issue by syrsly** [pusher/pusher-js#380] opened 2019-09-05 15:03 UTC
**Do you want to request a *feature* or report a *bug*?**
Probably a *bug* but could be considered a *feature* request as well?

**What is the current behavior?**
I save each channel to a "channels" array. Every channel is a presence channel, but each one is its own private chat room based on local chat ids. This is all fine until we try to get the members list. The list is null, but according to docs, this should be possible by running "presenceChannel.members". I've tried everything I can think of, but the only time the members object is available is when the subscription is first made. Afterward, even in the member_added and member_removed bindings, the object no longer exists.

**What is the expected behavior?**
I want to have an up-to-date members list for each and every room/channel. This is easily done with Chatkit, but Channels seems to be broken when it comes to this feature. Trying to dynamically add to and remove from this list using event logic does not work, because I cannot tell which channel the event was for. If someone knows how to get the channel name or chat room id along with the member_added and member_removed function callbacks, that would make a nice workaround.

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
As far as I know, it worked in previous versions of Pusher, because it's mentioned in the docs that this has been accomplished with some example code, but I cannot confirm this at this time. It could simply be a bug dealing with channels saved to an array object container. I'm using the latest version via composer, which was posted 3 days ago, but I've also tested previously with the initial v5.0.0 release. Neither have this feature working AFAIK.

Again, I'm ok with a workaround. For now, I'm handling only one chat's members at a time via unbinding and rebinding events and keeping the currently active/maximized chat's id in a globally accessible variable, and I don't necessarily need a solution to this problem. It just seems as though my own workaround shouldn't be necessary since docs say to do things another way. Also, it seems like these events should return channel names at the least, but docs do not say how to get this data.

**Comment by leesio** [comment] 2019-09-06 13:05
@joshmaines thanks for mentioning this it sounds like it could be quite serious.

At the moment, I can't reproduce the behaviour you're describing. Are you able to provide a bit more information about when the members list is null? It would be helpful if you could show a snippet of code showing how I can reproduce this issue.

**Comment by joshmaines** [comment] 2019-09-06 13:47
The members object is null outside of the scope of the subscription_succeeded event, so this works:

`var channels[id] = pusher.subscribe('presence-example');
channels[id].bind('pusher:subscription_succeeded', function() {
  var me = presenceChannel.members.me;
  var userId = me.id;
  var userInfo = me.info;
});`

However, this does not (returns null for members object):

`channels[id].bind('pusher:member_added', function(member) {
  if (channels[id].members.get(member.id)) {
    add_member(channel_name, member.id, member.info);
  }
});`

Keep in mind that this is a modified example code and not my actual code, because my actual working code is a full project and not a test project. The issue is making a "whos online" functionality a lot more difficult to handle, but it isn't impossible to accomplish my goals without the members object. There are plenty of workarounds, including using the PHP API and an ajax script (checking via ajax each time a member_added or member_removed event is heard. It would be nice if I could get the channel information in those events, though. Is that possible?

**Comment by leesio** [comment] 2019-10-07 09:02
Hi @joshmaines I spent a bit of time looking into your issue again this morning. I'm still having trouble seeing the issue. 

I created a [codepen](https://codepen.io/leesio/pen/VwwwoVG?editors=1111) with a simple based on the snippets you shared but everything works as I expect.

I'm sure I must be missing something could you help me see what it is?

**Comment by joshmaines** [comment] 2019-10-07 18:33
In your codepen, you check a specific channel listener with this code:
`presenceChannel.members.get(member.id)`

But in my example, I had an array of channel listeners, so I'd have to loop through every channel to see if the member exists. When I go through that loop (which gets slow when you have a lot of channels subscribed to), it returns the members object as undefined. This is really 2 issues, both that the members object is undefined and the act of looping through all the channels should be avoidable but isn't. Is there perhaps a way to do this without looping and without manually coding each channel listener?

**Comment by leesio** [comment] 2019-10-07 19:44
Right. I think I know what you're saying:

1. You have an `Array` of presence channels and you want be able to check whether a specific user is present in *any* of the presence channels in your `Array` without looping through the array and checking each channel?

1. Sometimes when you try to query the `members` object (in my example `presenceChannel.members.get(member.id)` `presenceChannel.members` is undefined?

Is that correct?

**Comment by joshmaines** [comment] 2019-10-24 17:05
Correct, leesio. The members object is undefined in v5 as well as far as I could tell, but my code base no longer uses this functionality at all, so all I can do is perform quick tests. Basically, I have an array of channels, but each channel in the array should have its own members object yet does not have one (resulting in the 'undefined' error).

**Comment by leesio** [comment] 2020-01-28 10:34
@syrsly really sorry for the delay in getting back to you. Are you still experiencing this issue?

**Comment by syrsly** [comment] 2020-01-31 20:07
I still have this problem when trying to programmatically load members objects, yes. I can, however, access the members object from any predetermined listener object just fine when using the events, pusher:subscription_succeeded, pusher:member_added, and pusher:member_removed, and that would work for me... if the event told me which listener it was a part of. (I can't seem to figure out how to retrieve that information, but I'm sure there's a way to do that... somehow.) I've been avoiding using the members feature for the most part, but I am successfully using this feature for a who's online mechanic in a single channel successfully. I just can't use it for multiple channels programmatically.

**Comment by leesio** [comment] 2020-02-07 10:57
Looking at your issues again this seems like it's a javascript issue rather than a pusher-js issue.
I think the problem with your snippet is that you're trying to use the `presenceChannel` variable inside the callback. I can't see where this variable is declared, but is it possible it's overridden elsewhere?

```
var channels[id] = pusher.subscribe('presence-example'); channels[id].bind('pusher:subscription_succeeded', function() { 
  // where is presenceChannel defined???
  var me = presenceChannel.members.me;
  var userId = me.id;
  var userInfo = me.info;
});
```

What you could try is passing the channel to a function which returns your callback function. This wraps the channel variable in a closure, so your callback should be able to refer to the channel it's bound to.

```
channels[id] = pusher.subscribe('presence-example');
channels[id].bind('pusher:subscription_succeeded', getBindFn(channels[id]))

funtion getBindFn(channel) {
  return function() {
    var me = channel.members.me;
    var userId = me.id;
    var userInfo = me.info;
  }
});
```

Does this make sense? Does it help?

**Comment by leesio** [comment] 2020-07-07 10:09
@syrsly I'm going to close this issue as it's been a while since I've heard from you.

Feel free to reopen it if you're still having problems.

**Closed by leesio** 2020-07-07 10:09 UTC
