### ISSUE TITLE
Service worker does not work on iOS 12.2 (Safari)

### ISSUE THREAD

**Issue by ccaseypusher** [pusher/pusher-js#347] opened 2019-05-28 10:03 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When the service worker connects, the connection state just resolves to unavailable. This was working on iOS versions < 12.2. This also works on the iOS simulator running iOS 12.2.

The suggestion is that this could be related to header support in Safari, however a demonstration of using headers in another application was successful

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

Connect to channels using a service worker. The issue occurs even without an authentication endpoint being provided.

**What is the expected behavior?**

The service worker should connect to channels

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**

Latest version of pusher-js/ iOS 12.2 / Safari

**Comment by leesio** [comment] 2019-06-20 20:25
I was able to recreate this issue in iOS 12.3.1 on a real device but not on a simulator running 12.2.

The library can't connect because `Websocket` connections seem to no longer work in Safari Service Worker contexts. I'm not sure why that is, but Ive created a ticket with apple to try and understand whether this was a deliberate change or a regression.

**Comment by leesio** [comment] 2019-07-18 13:09
Small update: I haven't received any update on the 'feedback' I submitted to Apple about this issue. However, based on [this thread](https://twitter.com/bradeeoh/status/1151562849962958848) involving @jameshfisher and Brady Eidson (the contact for the [Service Worker feature in WebKit](https://webkit.org/status/#specification-service-workers)), it seems like this _should_ work and the fact that it doesn't suggests it's a bug in iOS Safari.

**Comment by leesio** [comment] 2019-07-31 09:44
*Update* it seems this is indeed to due to a bug in webkit (the browser engine that powers Safari). 

The issue has been fixed in webkit, you can find a full description of the bug [here](https://bugs.webkit.org/show_bug.cgi?id=199906).

It's not clear when this fix will make it into safari but that release could be expedited if the customer impact is sufficiently high. With that in mind, if you're affected by this issue could you please add a comment describing:

- *What your application/website is*
- *How this bug is affecting your application/website*

**Comment by leesio** [comment] 2019-09-25 19:19
I just tested this again with the latest version of iOS 13.1 and everything seems to work as expected now.

With that I'm going to close this issue

**Closed by leesio** 2019-09-25 19:19 UTC
