### ISSUE TITLE
Add pusher-js to npm package registry

### ISSUE THREAD

**Issue by grin** [pusher/pusher-js#84] opened 2014-10-13 09:34 UTC
Would be helpful for those who use npm for front-end dependencies. Any plans?

**Comment by leggetter** [comment] 2015-01-15 01:16
I've made a first attempt at supporting CommonJS includes by adding a UMD wrapper.

I've done a simple build with Browserify and tested Flash and HTTP fallback. I'd certainly appreciate it if others could test this. You can grab the built version of this here:
https://gist.github.com/leggetter/1c1658f0555a1a94180a

It's important to point out that:

* this is just a quick attempt that I've put together and isn't suitable for production
* that files for fallback dependencies e.g. JSON, Flash connections, HTTP connections are still loaded from the Pusher CDN for the released 2.2.3 version of pusher-js. This probably won't change if we release this.

However, this should let people include an use pusher-js via NPM and build with Browserify which I believe is the main objective.

If this UMD header appears to work we may be able to include it in a future pusher-js release and then we can start publishing it on npm as part of our release process. But there's a bit of testing that needs to be done before we do that and a decision about the version that gets the UMD header.

Please let me know if you have any feedback or questions about this.

**Comment by mwjackson** [comment] 2015-01-19 14:05
@leggetter when are you planning to release this change?

**Comment by leggetter** [comment] 2015-01-21 01:48
@mwjackson - I'm working towards making sure that I can run all the tests we have against the pusher-js version that's been built with a UMD wrapper.

I've got the unit tests running and passing but I need the integration test suite to be passing before I'd be happy to release it. Hopefully this can be done within a week.

**Comment by terebentina** [comment] 2015-02-25 15:34
+1 for the umd wrapper. The sooner the better, please

**Comment by leggetter** [comment] 2015-03-03 18:13
Update: we have an internal version of this working and tested with Browserify. However, we've taken the opportunity to look into migrating the build process to more common node-based tooling. This includes testing, building and deployment processes.

We could release an early version, but there are some unanswered questions related to versioning and loading dependencies from a CDN. I'll try to speak to @pl about this over the next few days.

Sorry that it's taking so long to get this out.

**Comment by naorye** [comment] 2015-03-15 09:21
Any news regarding this?

**Comment by leggetter** [comment] 2015-03-15 10:02
The plan is for it to be in v3.0 of the library. It will contain:

* UMD support
* Remove Flash fallback (HTTP fallback is already in place and will be used instead)
* Build and deployment tooling will be migrated from Ruby to Node

We'll try to get an alpha (a full version release may be quite a bit longer) of this out within the next three weeks. But it depends on what's prioritised and how much time we get to spend on library development. Fingers crossed an I will update this thread if there's any progress.

**Comment by juliankrispel** [comment] 2015-03-30 01:29
Would be great to have that :+1:

**Comment by jhollingworth** [comment] 2015-04-01 11:21
:+1:

**Comment by zimbatm** [comment] 2015-04-01 14:47
Quick update, @pl has been working on moving the deployment tools to node but it's a bit more difficult that we hoped. We're pondering options

**Comment by mwjackson** [comment] 2015-04-01 14:51
Do you need to convert your build tools to node to release a UMD wrapper?

**Comment by juliankrispel** [comment] 2015-04-01 16:53
@zimbatm just use [UMD](https://github.com/umdjs/umd)

**Comment by leggetter** [comment] 2015-04-01 17:29
@mwjackson @juliankrispel We are using UMD. Specifically we're using https://github.com/umdjs/umd/blob/master/commonjsStrictGlobal.js

Right now the library internals have dependencies on a global `Pusher` object so this seemed the best choice.

> Do you need to convert your build tools to node to release a UMD wrapper?

There are a number of reasons for the move to a different set of tooling.

1. The current test suite works against unbuilt (non-concatenated) files. We obviously wanted to test the full built version and it seemed easier to do this using new tooling that to work with our own tooling which we have to maintain (there was a tricky use case here that I can't remember the full details of).
2. We don't really want to fully maintain our own build tooling so fully using existing common tooling is a good move. If need be, we can simply contribute changes to existing projects.
3. We want it to be easier for others to contribute to pusher-js; if this was an easy fix then we should of got a PR that we could merge [without issue](https://github.com/pusher/pusher-js/pull/47#issuecomment-34427204). But we haven't, so there's a problem there that we'd like to resolve. By moving to commonly used tooling where everybody can easily run the tests, perform builds etc. we're hoping things will improve.
4. We want to remove Flash fallback and just use HTTP fallback instead. Doing this actually simplifies the build process. It was easier to add UMD support + new tooling without a Flash build dependency :tada: 
5. We're presently adding an improvement to the platform that requires a library change, so all of this was rolled into that process.

Right now we have a branch in a private repo that works.... but we can't test in IE6 or IE7 due to problems with the Node-based Jasime test runner :hankey:.

Hopefully that clarifies why this isn't as easy as top and tailing the existing script with a UMD header and footer. And *hopefully* we'll be able to solve the IE6 and IE7 testing problem (we do have customers who need this).

**So, if anybody knows of a Gulp-based Jasmine 2.0 Test Runner that works in IE6+ please let us know**

**Comment by juliankrispel** [comment] 2015-04-01 19:20
@leggetter thanks for shining a light on this

**Comment by zimbatm** [comment] 2015-04-02 10:44
Another solution would be to drop IE6 and IE7 support for the new lib. IE6+SSL is already broken because we removed SSLv3 support a while ago to prevent the POODLE attack.

**Comment by mwjackson** [comment] 2015-04-02 11:00
I guess the question is whether those customers can continue to use the old version for their IE6/7 support. We don't have that requirement (thank god), so obviously the sooner you can get this out the better.

**Comment by zimbatm** [comment] 2015-04-02 11:07
And we could drop the JSON polyfill.

Just as a curiosity, why do you guys want npm packaging, to manage your dependencies with a single tool ?

**Comment by jhollingworth** [comment] 2015-04-02 11:11
We use browserify so would like to just `npm install pusher-js`. right now I've got to have a separate script file just for pusher and then include pusher in via a shim which is really ugly...

**Comment by mwjackson** [comment] 2015-04-02 11:15
We have a similar situation to @jhollingworth, but using webpack.

**Comment by terebentina** [comment] 2015-04-02 11:17
It's not so much about npm as about being able to use a build tool to build/pack/uglify/version/etc our frontend code. Having pusher-js built into our codebase is cleaner, saves a http request, we don't need to worry about cdn availability. Also, we can lock all dependencies (including pusher-js) to a certain version that we know works.
If you add umd to pusher-js you don't actually need to publish to npm, although it's more convenient for us to do so. We can install pusher-js straight from github if everything is configured correctly. Also note that it's enough if you publish just the build files (.npmignore the sources folder).

**Comment by leggetter** [comment] 2015-04-02 11:30
Thanks for the clarification.

We'll consider browser support (can we drop IE6/7 in the 3.0 release?) and try to get something out soon. I personally love tools like Browserify and webpack so really want to make sure pusher-js doesn't get in the way of the great developer experience that they provide.

We'll obviously update this issue once we have more info.

**Comment by jhollingworth** [comment] 2015-04-02 11:32
IE<8 isn't a concern for us at all

**Comment by m4tthumphrey** [comment] 2015-04-02 13:37
webpack :+1:

**Comment by DanielApt** [comment] 2015-04-02 14:53
[Testling](https://ci.testling.com/) this could maybe address the testing for IE7.

**Comment by iclanzan** [comment] 2015-04-03 18:09
Thank you guys for working on this. :+1:

**Comment by zimbatm** [comment] 2015-04-23 16:54
Alright. I've got a r3.0.0 branch with UMD and a couple of other things. Anyone wants to test it out ?

**Comment by marcbachmann** [comment] 2015-04-23 17:02
I'll try it.

**Comment by zimbatm** [comment] 2015-04-23 17:34
For browser testing you can also go directly to http://test.pusher.com/?version=3.0.0 and play around with the client

**Comment by terebentina** [comment] 2015-04-24 16:30
I got the chance to play a bit with the new 3.0.0 branch today.
There is a problem here: https://github.com/pusher/pusher-js/blob/r3.0.0/dist/pusher.js#L23
['Pusher'] there means the library (pusher-js) depends on a package named "Pusher".
The line should read:
```javascript
define([], function () {
```

I manually changed and tested and it works fine in latest ff and latest chrome on windows. Haven't got the chance to do more tests but will surely do in the following days.
Will submit a PR in a bit.

Fun fact: I did actually have a "pusher" module installed (the node.js client) and all hell broke lose when I tried to compile as it was trying to load that module to satisfy the dependency. Without the "pusher" module it would simply say "pusher module not found".

**Comment by zimbatm** [comment] 2015-04-24 16:49
Thanks @terebentina, I'll update src/build/umd_header.js to match what you said.

**Comment by zimbatm** [comment] 2015-04-24 17:10
I have made another build with the updated headers if you want to give it another try

**Comment by terebentina** [comment] 2015-04-24 17:25
Yep, ok, will test tomorrow.

**Comment by terebentina** [comment] 2015-04-27 11:32
Ok, this works fine now. For the record, I bundle my files with webpack. Maybe someone who uses browserify could test it too?
I tested with chrome and ff win latest, android 4.4 chrome and default browser and with mobile safari 7.0, no problems.

**Comment by marcbachmann** [comment] 2015-04-27 11:39
:+1: I've just tested it using browserify. Works like before in Firefox & Chrome.

**Comment by juliankrispel** [comment] 2015-04-27 12:35
Awesome +1

**Comment by leggetter** [comment] 2015-05-07 16:59
```
npm install pusher-js
```

:rocket: :fireworks: :astonished: :tada: :balloon: 

This is strictly still a release candidate, but I've used it a bit and it seems "all good" to me. I've also created a super-simple reference here really just to check things build and work as expected:
https://github.com/pusher/pusher-js-npm-basics

Please leave any feedback here.

**Sorry this has taken SOOOOO long**

**Comment by leggetter** [comment] 2015-05-13 17:23
Since there hasn't been any further feedback and pusher-js is in NPM I'm going to close this issue.

Thanks to everybody that contributed. We'll officially announce the release pusher-js 3.0.0 shortly.

**Closed by leggetter** 2015-05-13 17:23 UTC

**Comment by DanielApt** [comment] 2015-05-15 14:17
We're sadly seeing issues with webpack. @m4tthumphrey could you tell me what you did to get it working?

We get the following warning:
```
WARNING in ./~/pusher/~/request/lib/optional.js
Critical dependencies:
11:13-32 the request of a dependency is an expression
 @ ./~/pusher/~/request/lib/optional.js 11:13-32
```

Followed by many errors all related to `request`:
```
ERROR in ./~/pusher/~/request/request.js
Module not found: Error: Cannot resolve module 'net' in /Users/danielapt/Desktop/pusher/node_modules/pusher/node_modules/request
 @ ./~/pusher/~/request/request.js 36:10-24

ERROR in ./~/pusher/~/request/~/tunnel-agent/index.js
Module not found: Error: Cannot resolve module 'net' in /Users/danielapt/Desktop/pusher/node_modules/pusher/node_modules/request/node_modules/tunnel-agent
 @ ./~/pusher/~/request/~/tunnel-agent/index.js 3:10-24

ERROR in ./~/pusher/~/request/~/tunnel-agent/index.js
Module not found: Error: Cannot resolve module 'tls' in /Users/danielapt/Desktop/pusher/node_modules/pusher/node_modules/request/node_modules/tunnel-agent
 @ ./~/pusher/~/request/~/tunnel-agent/index.js 4:10-24

etc...
```

To reproduce please check out this repo:
https://github.com/DanielApt/webpack-pusher

**Comment by leggetter** [comment] 2015-05-15 16:17
Sound like you are using "pusher". The NPM module for the browser library
is "pusher-js".

**Comment by DanielApt** [comment] 2015-05-15 16:18
Whoops… * facepalm *

**Comment by joshhornby** [comment] 2015-07-03 10:34
I am trying to use the NPM package in a React application. I am importing the package like so:

```import Pusher from "pusher-js";```

But when I compile with webpack I get the following error:

```
node_modules/pusher-js/dist/pusher.js:1196
  if (!window.JSON) {
       ^
ReferenceError: window is not defined
```

Any ideas?

**Comment by DanielApt** [comment] 2015-07-03 10:57
@joshhornby Use CommonJS syntax to import pusher-js:
`require('pusher-js);`

We've been successfully using pusher-js with webpack.

**Comment by joshhornby** [comment] 2015-07-03 10:59
@DanielApt Thanks for the advice.

Still getting the same error about the window not being defined. Have you used this is a react application?

**Comment by DanielApt** [comment] 2015-07-03 11:41
@joshhornby No, we haven't used it in combination with a react app. I'm a bit stumped on this one…

What is the target of your webpack project? Window being undefined would make me think it's set to `node`, instead it should be `web`. Maybe [the target documentation](http://webpack.github.io/docs/configuration.html#target) helps you.

**Comment by leggetter** [comment] 2015-07-06 11:41
@DanielApt I'd suggest going back to basics and working out where the problem is introduced. There's a very basic webpack example here:
https://github.com/pusher-community/pusher-js-npm-basics

How about starting there and building up to include react etc.

Or have you resolved the problem now?

**Comment by DanielApt** [comment] 2015-07-07 10:08
@leggetter This is actually @joshhornby's issue, not mine. Anyways… @joshhornby I suggest you look at the above comment.

**Comment by joshhornby** [comment] 2015-07-07 14:47
Thanks @leggetter will take a look.

**Comment by everblaze** [comment] 2015-08-21 03:05
was there any resolution to this error im getting the same..

**Comment by everblaze** [comment] 2015-08-21 03:31
Never mind worked out what the problem was to do with isomorphic application when using react. It was requiring the lib while on the server before hydrating to the client.

**Comment by coderholic** [comment] 2016-03-30 20:43
@everblaze @joshhornby how did you resolve this? I'm getting the same error with a react app.

**Comment by jackfranklin** [comment] 2016-04-01 10:47
@coderholic can you replicate the bug in a GitHub repo that we can look at?

I'd recommend checking out Phil's comment above [https://github.com/pusher/pusher-js/issues/84#issuecomment-118828651] and going from there.
