### ISSUE TITLE
channel.trigger() seems to be blocked/delayed on AWS Amplify and Vercel

### ISSUE THREAD

**Issue by linkfang** [pusher/pusher-js#664] opened 2022-12-12 16:50 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I have a simple test Next.js web app, which contains a button to send a POST request to trigger the pusherHandler.

The current behavior is:
On AWS Amplify (free version), there are high chances that the event message will NOT be send to front end after a 200 response.

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

Open both an Amplify instance and a localhost instance. Both are connecting to the same channel and event.

On Amplify, click the button -> send out POST -> receive 200 response -> but no event message is send back (will very likely happen on the first attempt after open the web page) -> refresh the page -> the localhost then will receive the message.

On localhost, do the same actions, everything works well. I will NOT miss any event messages on both localhost and Amplify.

**What is the expected behavior?**
I would expect when deploy on Amplify, it will work the same as localhost version.

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
    "pusher": "^5.1.2",
    "pusher-js": "^7.5.0",

https://user-images.githubusercontent.com/43075439/207103463-bd98d890-fefa-47b1-81ec-fac9a9e3d832.mov

**Comment by benw-pusher** [comment] 2022-12-12 17:12
closing this as a duplicate of https://github.com/pusher/pusher-http-node/issues/183

**Closed by benw-pusher** 2022-12-12 17:12 UTC
