### ISSUE TITLE
Retry auth request on error

### ISSUE THREAD

**Issue by rcevs** [pusher/pusher-js#292] opened 2018-08-02 03:26 UTC
Hi.

I'm using JWT tokens for my app authentication. When the token expires my app automatically sends a retry request to refresh the token and repeats the original request.

This isn't happening with pusher-js. How can I get the response status and retry the request in case it fails the first time?

Thanks in advance!

**Comment by pietro909** [comment] 2018-11-02 14:49
We have exactly the same scenario. I'm wrapping the whole logic with promises to be able to chain and react in case of failure (using `pusher:subscription_error` and `pusher:error` events).

The issue is that *the authorize function is not called anymore* even when I try to re-subscribe.

**Comment by pnminh1710** [comment] 2019-06-19 05:16
Hi @pietro909 and @rcevs, have you guy resolved this problem.
You can try to update the auth token in pusher:subscription_error and call channel.subcribe, It will re send the pusher/auth to the sever.
But I can't find the right place to unbind the event pusher:subscription_error. Anyone have suggestion
`    channel.bind('pusher:subscription_error', status => {
      if (status === 401) {
        // get new token here.
        socket.config.auth.headers.Authorization = token;
        channel.subscribe();
        channel.unbind('pusher:subscription_error'); // should not unbind in here
      }
    });`

**Comment by leesio** [comment] 2020-01-28 11:26
I'm going to close this issue, as I think @pnminh1710 solution is the best way to resolve this issue - a word of warning though: there is a PR to change the data passed to the `pusher:subscription_error` handler #412 . It hasn't been merged and, if it is, will be a major version bump.

**Closed by leesio** 2020-01-28 11:26 UTC

**Comment by caseykhuc** [comment] 2023-02-01 11:33
Since `socket.config.auth.headers.Authorization` is not accessible in recent versions, @pnminh1710's solution is not possible anymore.

Any ways to trigger auth request? This is a real use case.
