### ISSUE TITLE
Connecting to a custom host in react-native

### ISSUE THREAD

**Issue by jafar-albadarneh** [pusher/pusher-js#319] opened 2019-01-09 23:51 UTC
I am trying to connect to a custom socket server on my local machine. I am using Laravel php, and i've setup  a socket server on my local machine using [Laravel/web-sockets](https://github.com/beyondcode/laravel-websockets), and it's working great. I have tested it using Laravel Echo with 'Pusher' as a broadcaster and it worked well on a sample web page.

I'm trying to connect to the socket server using react-native app through `pusher` client. I've installed the package and set the configurations as stated in the docs. As follows:
```javascript
let pusher = new Pusher("SomeRandomAppKey", {
         wsHost       : 'a731f023.ngrok.io',
         wsPort       : 6001,
         disableStats : true,
     });
```
Given that the `wsHost` is shared via ngrok from my machine.
In order to debug if the connection works, i've bound the status event to the connection, as follows:
```javascript
pusher.connection.bind('state_change', function(states) {
        console.log("Channels current state is " + states.current);
    });
```
The status returned in `unavailable`.

What i am missing here? I need to get it to work.

The current version of `pusher-js` is **4.3.1**

**Comment by okaufmann** [comment] 2019-01-24 16:33
I have the exact same problem using `pusher-js` in a Node CLI app. I can connect to any local servers (via 127.0.0.1 or hostnames resolved to this IP). Of course it works with all the official Pusher servers. But when I connect to my own hosted Pusher compliant server I also get `unavailable`...

Is this blocked by the client in any way?

**Comment by okaufmann** [comment] 2019-01-29 18:07
Finally I found out that it was a problem with the ssl configuration. I couldn't figure out which one but if the certificate verification is turned off (insecure) it works. 

As I am using Node I did this with

    NODE_TLS_REJECT_UNAUTHORIZED=0 node index.js
    // or
    process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = 0;

After hours of trying to find the correct nginx proxy settings I gave up...

**Comment by leesio** [comment] 2019-02-01 16:02
@okaufmann Looks like you solved your issue. Just to be clear though:

> Is this blocked by the client in any way?

No. pusher-js should be able to speak to any server that conforms to the [channels protocol](https://pusher.com/docs/pusher_protocol)

@jafar-albadarneh it's really hard to say what could be causing your issue as you're not trying to connect to a pusher-server. The state will be updated to `unavailable` if the connection process times out before a handshake completes.

One thing it's worth checking though: I think if you're running `ngrok` in the simplest way:

```
ngrok http 6001
```

Your local machine port 6001 will be on a731f023.ngrok.io:80. So you might want to try removing the `wsPort` argument from your pusher config.

**Comment by okaufmann** [comment] 2019-02-01 16:23
The issue is partially solved. If I connect my custom pusher server (using laravel-websockets) via Port 80 its works without any problems. If I switch to wss and port 443 I'm getting unavailable (via Node). If I setup the same client in a browser it works for both ways.

As my setup is not that security relevant I go with setting `NODE_TLS_REJECT_UNAUTHORIZED` to `0` and it starts working when I connect with wss...

I don't get any logs on the server nor the client helping solving the exact reason causing this behaviour. I started comparing my ssl setup with a official pusher server ones and can't find any relevant differences (not a ssl expert though).

For me this issue here is closed as I think its not the exact same problem like the one @jafar-albadarneh has.

**Comment by leesio** [comment] 2019-02-02 11:07
@okaufmann thanks for the update. Have you enabled logging in the library?

```
Pusher.logToConsole = true;
```

**Comment by leesio** [comment] 2019-07-23 08:21
I'm going to close this issue as I belive it to be resolved. If there's more to add, please feel free to re-open the issue.

**Closed by leesio** 2019-07-23 08:21 UTC
