### ISSUE TITLE
This Line Cannot Throw Error

### ISSUE THREAD

**Issue by sametsirinel** [pusher/pusher-js#583] opened 2022-03-08 13:43 UTC
https://github.com/pusher/pusher-js/blob/91459e12053d0362e6356e27800a0f2fcab52f5e/src/core/channels/channel.ts#L123

We have been losing quiet some times at this part.

We have completed the authentication part, we are getting response and everything is fine. However, when we send empty response with our response variable to  your callback function, it does not throw us the exception.

We have solved the problem. However, we got lucky solving the problem. If anyone else faces the same problem, they would not know what to do and require help due to it is not throwing exception.

![image](https://user-images.githubusercontent.com/16854006/157249447-8679fb2c-6a6b-4a14-9f74-4a36af73ee7e.png)

**Comment by benw-pusher** [comment] 2022-03-08 14:01
Thanks for sharing. This appears to be an issue in your custom code where it is not returning the auth string. Our documentation at https://pusher.com/docs/channels/server_api/authenticating-users/ shows that an auth string is required. 

I'll look at making this more explicit in the docs however this is not a bug with the library so I will close this issue.

**Closed by benw-pusher** 2022-03-08 14:01 UTC
