### ISSUE TITLE
Pusher-js connection state suddenly becomes `failed` after a wifi outage

### ISSUE THREAD

**Issue by tonygaetani** [pusher/pusher-js#206] opened 2016-12-08 16:27 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
intermittent wifi outages cause connection state to become `failed`

**minimal demo of the problem**
index.js:
```
const Pusher = require('pusher-js/node');

Pusher.logToConsole = true;

const app_id = 'foo';
const options = {
	'httpHost': 'foo.com',
	'httpPort': 4567,
	'wsHost': 'foo.com',
	'wsPort': 8081,
	'scheme': 'http',
	'encrypted': false,
	'authEndpoint': 'bar.com',
	'activityTimeout': 1000,
	'pongTimeout': 2000,
	'unavailableTimeout': 1000,
	'enabledTransports': ['ws'],
	'auth': {
		params: {
			userId: 0,
			userType: 'bot'
		}
	}
};

const pusher = new Pusher(app_id, options);

pusher.connection.bind('connected', () => console.log('connected'));
pusher.connection.bind('connecting', () => console.log('connecting'));
pusher.connection.bind('connecting_in', () => console.log('connecting_in'));
pusher.connection.bind('disconnected', () => console.log('disconnected'));
pusher.connection.bind('unavailable', () => console.log('unavailable'));
pusher.connection.bind('error', (err) => console.log({err}, 'error'));
pusher.connection.bind('failed', (err) => console.log({err}, 'failed'));

const channel = pusher.subscribe('presence-test_0');
channel.bind('pusher:subscription_succeeded', () => console.log('pusher subscription succeeded'));
```

package.json
```
{
  "name": "pusher-js-bug",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "license": "ISC",
  "dependencies": {
    "pusher-js": "^3.2.4"
  }
}
```

run using nodejs/npm
```
npm install
node index.js
# now start toggling your wifi on/off
```

**What is the expected behavior?**
Connection should be recovered, or at least continue to retry connecting. Connection state should presumably not become `failed` after the same configuration has been working.

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
Platform: x64
Arch: both darwin and arm7l
Runtime: nodejs
Pusher version: 3.2.4 (this does not appear to be a new issue)
The issue does not appear to occur on the same machine using browser runtime instead of nodejs runtime.

The pusher-js documentation does not explicitly state that pusher's connection state should not change from `connecting -> connected -> connecting -> unavailable -> connecting -> connected -> failed`, but it seems to me that the docs hint that that series of state changes should not be possible. This is what I am seeing (sometimes) with the above sample code even if I just toggle my wifi on and off a few times. I am seeing this issue while running pusher-js on a device that moves around in a building with unreliable wifi. Sometimes the wifi connection is lost, in which case pusher-js connection state changes from `connected -> connecting -> unavailable` and when wifi comes back the state changes from `unavailable -> connecting -> connected`. However, sometimes pusher-js connection state becomes `failed`. The docs say that connection state failed means "Pusher is not supported by the browser. This implies that WebSockets are not natively available and an HTTP-based transport could not be found." In my case pusher-js is using websockets transport happily, loses wifi connection, then suddenly becomes `failed`. The docs also hint that pusher-js connection state can only change to `failed` immediately after `initialized`, the examples show "In the case that Pusher is not supported: initialized -> failed". But in my case Pusher _is_ supported, it just suddenly stops working and becomes failed.

Here are the docs I'm referencing:
https://pusher.com/docs/client_api_guide/client_connect#available-states

**Comment by tonygaetani** [comment] 2016-12-08 16:28
@jbcpollak

**Comment by jbcpollak** [comment] 2017-01-24 22:59
any progress on this? It is causing significant problems for us on spotty internet connections

**Comment by hph** [comment] 2017-01-25 10:44
Hi, there! I'm sorry for the lack of progress and communication on this issue. I did attempt to reproduce it with the code sample you've provided but I was unable to, concluding that it would require further investigation. Unfortunately I'm occupied with other tasks right now, but I can take a second look at this issue as soon as next week.

**Comment by tonygaetani** [comment] 2017-01-25 14:55
@hph can you confirm that it is odd behavior for a pusher connection state to change from `connecting -> connected -> connecting -> unavailable -> connecting -> connected -> failed` ? I would like to know if I'm misusing the library or if that sounds like it's probably a bug in pusher-js for node. The docs hint that a pusher connection state should never change from `connected` to `failed`.

**Comment by hph** [comment] 2017-02-02 10:16
@tonygaetani That definitely is odd behaviour, especially considering that I haven't been able to reproduce it.

**Comment by tonygaetani** [comment] 2017-02-02 15:30
@hph I suspect that the root cause is something to do with the handling of WebSocket CloseEvents https://github.com/pusher/pusher-js/blob/0ef56995ed9605b79ba4b22d1a13c84652d47793/src/core/connection/protocol/protocol.ts#L93

I should have mentioned that I am not using production pusher backend, I'm using https://github.com/stevegraham/slanger as a backend.

**Comment by hph** [comment] 2017-02-02 16:53
That could explain why I was not able to reproduce the problem. I'm closing this issue because it does not pertain to the Pusher platform. Feel free to reopen it if you manage to reproduce it against our servers.

**Closed by hph** 2017-02-02 16:53 UTC
Labels: Bug

**Comment by tonygaetani** [comment] 2017-02-02 17:19
Okay, understandable. Thanks for investigating anyway @hph

**Comment by Hillcow** [comment] 2021-06-21 17:19
Same issue here with Laravel Echo.
