### ISSUE TITLE
Pusher websocket URL triggering events and sending data

### ISSUE THREAD

**Issue by sushilsth** [pusher/pusher-js#820] opened 2024-05-18 16:15 UTC
I am trying to trigger events and send data to websocket URL on the specific public channel. I am currently testing in postman. I am able to connect to websocket URL and subscribe to the channel but cannot trigger events and send data to the event.

Here is what I have tried. I can connect to websocket URL and subscribe to the channel as screenshot below.

![image](https://github.com/pusher/pusher-js/assets/7147132/035f71a7-c104-46b9-a958-a5429513e27c)

Now when I try to trigger event and send data, it throw the error as marked in screenshot below. Here is the error in pusher response Unsupported event received on socket: my-event"

![image](https://github.com/pusher/pusher-js/assets/7147132/b635249a-1e8f-40ed-9ecb-5a897be949fd)

As per the official docs of pusher https://pusher.com/docs/channels/library_auth_reference/pusher-websockets-protocol/#channel-events-pusher-channels-greater-client,

This should be the correct way to trigger events but it is not working. Can anyone help me with this?

Thank you

**Comment by benw-pusher** [comment] 2024-05-20 09:00
Duplicate of https://github.com/pusher/pusher-http-php/issues/387

**Closed by benw-pusher** 2024-05-20 09:00 UTC
