### ISSUE TITLE
.git directory present within module

### ISSUE THREAD

**Issue by electrified** [pusher/pusher-js#276] opened 2018-04-11 10:44 UTC
This is a really minor issue but thought it was worth reporting :)

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
There is a .git directory present within the module at the following path: ```src/runtimes/web/dom/sockjs/.git```

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

During our build process we do a ``` git clean -fdx``` which results in the following error:

```fatal: Not a git repository: node_modules/pusher-js/src/runtimes/web/dom/sockjs/../../../../../.git/modules/sockjs-client```

**What is the expected behavior?**
No extraneous .git directories

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
Unsure when the issue was introduced, but it exists in 4.1.0 and 4.2.2

**Comment by AlexanderVangelov** [comment] 2018-06-11 17:54
It breaks commands like "git clean -fdx" returned status code 128:
stdout: Removing node_modules/

stderr: fatal: Not a git repository: node_modules/pusher-js/src/runtimes/web/dom/sockjs/../../../../../.git/modules/sockjs-client

**Comment by willedwards** [comment] 2018-06-17 13:04
node_modules should normally not be checked in. 
You probably need to add node_modules to your .gitignore file

**Comment by AlexanderVangelov** [comment] 2018-06-18 13:48
@willedwards the command "git clean -fdx" is used to remove untracked directories (like node_modules/ added to .gitignore). But if an untracked directory is managed by a different git repository - it is honored.  Possible to force it with double -f but Jenkins git clean is using single -f by default.

**Comment by jeffberry** [comment] 2018-07-16 22:03
Any updates on this? We are experiencing the same issue. It seems to be the `sockjs` git module that is being cloned and preventing `git clean`

**Comment by leesio** [comment] 2019-02-06 12:00
I assume this issue was caused by somebody publishing to npm after initialising the submodule.
I'm sorry this happened, but I believe this is resolved now.

```
leesio pusher-js-install-test(deneb)$ npm install pusher-js
leesio pusher-js-install-test(deneb)$ ls node_modules/pusher-js/src/runtimes/web/dom/
total 88
drwxr-xr-x   9 leesio  staff   288B  6 Feb 11:52 .
drwxr-xr-x  11 leesio  staff   352B  6 Feb 11:52 ..
-rw-r--r--   1 leesio  staff   498B  6 Feb 11:52 dependencies.ts
-rw-r--r--   1 leesio  staff   2.6K  6 Feb 11:52 dependency_loader.ts
-rw-r--r--   1 leesio  staff    17K  6 Feb 11:52 json2.js
-rw-r--r--   1 leesio  staff   1.5K  6 Feb 11:52 jsonp_request.ts
-rw-r--r--   1 leesio  staff   131B  6 Feb 11:52 script_receiver.ts
-rw-r--r--   1 leesio  staff   1.5K  6 Feb 11:52 script_receiver_factory.ts
-rw-r--r--   1 leesio  staff   2.4K  6 Feb 11:52 script_request.ts
```

**Closed** 2019-03-08 13:59 UTC
