### ISSUE TITLE
Race condition in Safari 9 - "TypeError: null is not an object (evaluating 'o.abort')"

### ISSUE THREAD

**Issue by andrewk** [pusher/pusher-js#129] opened 2015-10-27 02:05 UTC
We're seeing this a lot in our bugsnag JS logs.

Caused by this line - https://github.com/pusher/pusher-js/blob/c492fbb1c44c08627fc44621fd3e7f7db1ba51f5/dist/pusher.js#L1822

Exclusively affects Safari 9 + OSX 10.10

Simplest path to preventing the error would be to check `runner.abort` exists before calling it.

**Comment by WillSewell** [comment] 2015-10-28 13:13
Thanks for reporting this issue @andrewk. We are currently looking into it and I will let you know once a fix is in place.

**Comment by zimbatm** [comment] 2015-10-29 19:53
@andrewk is there any way to reproduce the issue ? The error doesn't happen when using  http://test.pusher.com

**Comment by brianmcd** [comment] 2015-11-24 17:00
+1, seeing this in Rollbar

**Comment by zimbatm** [comment] 2015-11-24 18:29
I have upgraded to El Captain but am still not able to reproduce the issue. If anyone is able to or has a URL that I can hit that has the error please let me know. If you'd rather not share the URL publicly you can send a [support request](https://support.pusher.com/hc/en-us) and mention my name and/or link to this issue and I will take a look at it tomorrow.

**Comment by jpatel531** [comment] 2016-05-11 22:17
This should be fixed in 3.1 - feel free to reopen if it's not

**Closed by jpatel531** 2016-05-11 22:17 UTC
