### ISSUE TITLE
React-Native dangles connections on reload

### ISSUE THREAD

**Issue by Gerharddc** [pusher/pusher-js#266] opened 2018-01-14 07:55 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When you reload a React-Native app with an active Pusher connection, a new connection is created for every reload and they are only terminated when the app is completely terminated. Only the latest latest connection has a JS object to access it though but the rest still have "dangling" WebSocket connections.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Take any React-Native app and open a pusher connection somewhere without explicitly terminating it somewhere and check in the Pusher debug console that it just keeps building up new connections when you reload the app through the debug menu.

**What is the expected behavior?**
On a reload, either the existing WebSocket should be re-used or the old one should be destroyed before creating a new one.

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**

- Pusher-JS: 4.2.2

- React-Native: 0.51.0

It is probably broken in all versions...

**Comment by sergeylaptev** [comment] 2018-02-28 16:01
Completely agree with @Gerharddc we didn't release yet, and I was working with pusher in react-native, with reloading the app for sure. And got about 850 active connections. After closing the app connections were reduced to 0.

**Comment by CarlosRamon** [comment] 2018-08-01 13:59
The problem is that, every time the application is started, a new Pusher client is instantiated. Hence I try to list the channels of the current Pusher client and there really is only one. But in reality there are other Pusher clients from previous instances of the application. As the picture shows. every time I open the app, a new client is started and the previous client reference is lost by the application.

![captura de tela de 2018-08-01 10-35-41](https://user-images.githubusercontent.com/19677369/43526135-db1d4046-9579-11e8-885a-60ab6b8e0ea8.png)

I would like to know how to use the same Pusher client, or how to do so once a new Pusher with the same channel_id as the previous one has been created, a finished application can be terminated.

**Comment by quiromaniac** [comment] 2019-05-25 05:31
Hi, did you find any solutions? I'm stucked with the same problem!

**Comment by eightyfive** [comment] 2019-06-18 12:24
Hello,

I am in `__DEV__` mode, "Remote JS Debugging" & "Live Reload" enabled, only one TEST device connected, but my Pusher "Debug Console" shows an INSANE number of connections once I start my DEV app on my unique TEST device.

I believe it was not the case earlier on.

I tried to `--reset-cache` + uninstalling the app, but with no effect.

I don't really understand where do all these connections come from?

**Comment by auseika** [comment] 2019-07-04 09:22
Hi.
Still no solution?

**Comment by eightyfive** [comment] 2019-07-08 10:57
Hi @auseika 

In my case using the `activityTimeout` option was causing the problem (Android).

```js
  const client = new Pusher(key, {
    authEndpoint: `${Config.apiUrl}/broadcasting/auth`,
    cluster: 'us2',
    forceTLS: true,
    // activityTimeout: 6000, // Commenting option and... Voilà!
  });
```

Hope this helps.

**Comment by eightyfive** [comment] 2019-08-02 09:14
FYI the problem re-appeared in `__DEV__` mode only (still), but regardless of `activityTimeout` option being present or not.

**Comment by tareqdayya** [comment] 2019-09-03 16:33
same here.
react-native-cli: 2.0.1
react-native: 0.59.8
pusher-js: ^4.4.0

**Comment by fabiancarlos** [comment] 2019-09-18 22:46
having problems with that too

**Comment by madmod** [comment] 2020-02-25 19:17
I am also having this issue. Commenting out activityTimeout fixed it but then I have this (minor) issue. https://github.com/pusher/pusher-js/issues/239

**Comment by QuantJames** [comment] 2020-02-27 03:50
Same here. Any hope of a fix? Maxing out on our tier after a few minutes of development...

**Comment by tareqdayya** [comment] 2020-02-27 09:04
Right now, I just close the app and re-open it, and it takes care of it. It's a quick work-around. I just need to remember to do it.

**Closed** 2021-03-05 11:58 UTC
Labels: react-native, wontfix

**Comment by riderx** [comment] 2023-05-16 17:10
Hey do anymore found a solution ? self open and close is not a good solution

**Comment by oleanti** [comment] 2023-05-21 16:55
If you have made a function for connecting and one for disconnecting you can easily just do it like this in a component. No need to restart the app.
```
useEffect(() => {
    // Connect when mounting the component
    connect()
    
    // returned function will be called on component unmount 
    return () => {
      disconnect()
    }
},[])
  ```
