### ISSUE TITLE
event pusher:error not described in docs - can't get WebSocketError when using invalid key

### ISSUE THREAD

**Issue by Misiu** [pusher/pusher-js#289] opened 2018-07-23 12:11 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I'm trying to catch all possible errors when connecting to private channel. 
I followed [docs](https://pusher.com/docs/client_api_guide/client_events) and I added this event hander:

```
channel.bind('pusher:subscription_error',
  function (status) {
    if (status == 401)
    {
      console.log("event :: pusher :: connection error: " + status);
      alert("Invalid credentials");
    }
    else {
      console.log("event :: pusher :: connection error: " + status);
      alert("Other error");
    }
  });
```

However when testing my app I got this error:

> Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":{"code":null,"message":"Invalid key in subscription auth data: '37ed426eeff27e042d47'"}}}

This is because key I used was different.

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

Right now I had to add another event handler to **pusher** object, not to channel:

```
pusher.bind('pusher:error',
        function (status) {
          console.log("event :: pusher :: connection error", status);
        });
```

**What is the expected behavior?**
Those kind of event should be described in docs or `pusher:subscription_error` should handle it.

```
pusher.bind('pusher:error', function(status) {
});
```

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
https://js.pusher.com/4.1/pusher.js

Steps to reproduce:
when using private channels use different key in client code and in server code. Try to catch this error using events described in docs.

**Comment by leesio** [comment] 2018-08-06 12:54
Hi @Misiu, thanks for describing this issue.

I can confirm that this is the expected behaviour of the library. Since this problem manifest itself during the creation of the websocket connection (i.e. before channels can really 'exist') events are emitted on the pusher instance.

I do agree that the documentation should be more clear on this and I'll look into updating it.

**Comment by leesio** [comment] 2019-06-21 18:12
I added a note in the docs about this. @Misiu do you think this make it clearer?

https://pusher.com/docs/channels/using_channels/events#pusher-subscription-error

**Comment by Misiu** [comment] 2019-06-24 10:12
@leesio this looks better. However, this was reported so long ago, so I can't say this clear all the cases.
I'll verify that when I use Pusher in next project :)

One additional question: who is responsible for .NET library? Both client and server need .NET Standard support for new projects. Could You take a look at this?
https://github.com/pusher/pusher-http-dotnet/issues/47
https://github.com/pusher/pusher-websocket-dotnet/issues/45

**Comment by leesio** [comment] 2019-06-24 16:19
@Misiu cool, I'll close this ticket for now, feel free to reopen it if you have issues later on.

As for the .NET library, I've mentioned it to the library maintainer, he should be getting back to you right now.

**Closed by leesio** 2019-06-24 16:19 UTC
Labels: Documentation Problem
